services:
  postgres_unbound:
    container_name: unbound_postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: unbound_db
      POSTGRES_USER: unbound_user
      POSTGRES_PASSWORD: unbound_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_unbound_data:/var/lib/postgresql
  
volumes:
  postgres_unbound_data:
